name: Push File

on: push

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: pytorch-to-tflite/
          recursive: true
          dest: latest-pytorch-example.zip
      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/result.zip
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'pytorch-to-tflite'
        destination_repo: 'Arm-Examples/ml-embedded-test-repo'
        user_email: 'nina.drozd@arm.com'
        user_name: 'nindro01'
        commit_message: 'Example Sync'
