name: Synchronize ML-Examples repo

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - cmsis-pack-examples/**

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: cmsis-pack-examples/
          recursive: true
          dest: cmsis-pack-examples.zip
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.run_id }}
          release_name: Release ${{ github.run_id }}
          body: |
            CMSIS example packs release
          prerelease: false
          draft: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ${{ github.workspace }}/cmsis-pack-examples.zip
          asset_name: cmsis-pack-examples.zip
          asset_content_type: application/zip
      - name: Sync with repo
        run: |
          git clone https://.:${{ secrets.GITHUB_TOKEN }}@github.com/Arm-Examples/mlek-demos-on-Corstone-300 target
          7z x ${{ github.workspace }}/cmsis-pack-examples.zip target/
          cd target
          git add .
          git diff-index --quiet HEAD || git commit -m 'Example Sync - ${{ github.run_id }}'
          git push target main
